server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vega-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: vega-containers
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  - job_name: vega-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: vega-api
          component: api-server
          __path__: /var/log/vega/api.log
    pipeline_stages:
      - match:
          selector: '{job="vega-api"}'
          stages:
            - json:
                expressions:
                  level: level
                  timestamp: timestamp
                  message: message
                  module: module
            - labels:
                level:
                module:
            - timestamp:
                format: RFC3339
                source: timestamp

  - job_name: vega-federated-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: vega-federated
          component: coordinator
          __path__: /var/log/vega/federated.log
    pipeline_stages:
      - match:
          selector: '{job="vega-federated"}'
          stages:
            - json:
                expressions:
                  level: level
                  timestamp: timestamp
                  message: message
                  participant_id: participant_id
                  round: round
            - labels:
                level:
                participant_id:
                round:

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+):\s+(?P<message>.*)$'
      - labels:
          hostname:
          service:
      - timestamp:
          format: Jan 2 15:04:05
          source: timestamp