apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: vega-api-vpa
  namespace: vega-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vega-api
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: vega-api
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: vega-federated-vpa
  namespace: vega-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vega-federated-coordinator
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: coordinator
      minAllowed:
        cpu: 500m
        memory: 512Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
  namespace: vega-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: redis
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits