global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@vega.local'
  smtp_auth_username: 'alerts@vega.local'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://vega-api:8000/api/v1/alerts'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'alertmanager'
        password: 'webhook-secret'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@vega.local'
    subject: '[CRITICAL] Vega 2.0 Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-critical'
    title: 'Vega 2.0 Critical Alert'
    text: |
      {{ range .Alerts }}
      🚨 *{{ .Annotations.summary }}*
      *Instance:* {{ .Labels.instance }}
      *Severity:* {{ .Labels.severity }}
      *Time:* {{ .StartsAt }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'team@vega.local'
    subject: '[WARNING] Vega 2.0 Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-warning'
    title: 'Vega 2.0 Warning'
    text: |
      {{ range .Alerts }}
      ⚠️ *{{ .Annotations.summary }}*
      *Instance:* {{ .Labels.instance }}
      *Time:* {{ .StartsAt }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']