# Example Federated Learning Participants Configuration
# ===================================================

# Participant 1: Balanced Capabilities
participant_1:
  id: "participant_1"
  host: "127.0.0.1"
  port: 8001
  capabilities:
    cpu_cores: 8
    memory_gb: 16
    gpu_available: true
    gpu_memory_gb: 8
    storage_gb: 100
    network_bandwidth_mbps: 1000
  
  # Pruning-specific settings
  pruning_preferences:
    max_sparsity: 0.8
    preferred_methods: ["magnitude", "structured"]
    compute_budget: "medium"
    quality_priority: "balanced"

# Participant 2: High-Performance Node
participant_2:
  id: "participant_2" 
  host: "127.0.0.1"
  port: 8002
  capabilities:
    cpu_cores: 16
    memory_gb: 64
    gpu_available: true
    gpu_memory_gb: 24
    storage_gb: 500
    network_bandwidth_mbps: 10000
  
  # Pruning-specific settings
  pruning_preferences:
    max_sparsity: 0.9
    preferred_methods: ["gradient", "structured", "magnitude"]
    compute_budget: "high"
    quality_priority: "performance"

# Participant 3: Resource-Constrained Node
participant_3:
  id: "participant_3"
  host: "127.0.0.1"
  port: 8003
  capabilities:
    cpu_cores: 4
    memory_gb: 8
    gpu_available: false
    gpu_memory_gb: 0
    storage_gb: 50
    network_bandwidth_mbps: 100
  
  # Pruning-specific settings
  pruning_preferences:
    max_sparsity: 0.95
    preferred_methods: ["magnitude"]
    compute_budget: "low"
    quality_priority: "efficiency"

# Global orchestration settings for participants
orchestration:
  coordinator_host: "127.0.0.1"
  coordinator_port: 8000
  max_participants: 10
  min_participants: 2
  participant_timeout: 30
  heartbeat_interval: 5