# frogbot-config.yml
# Place this file at: .frogbot/frogbot-config.yml

- params:
    git:
      repoName: your-repo-name         # Mandatory: the name of your Git repository
      branches:
        - main                         # Branch(es) to scan (e.g., main, master, dev)

      # Optional templates for PR handling:
      # branchNameTemplate: "frogbot-${IMPACTED_PACKAGE}-${BRANCH_NAME_HASH}"
      # commitMessageTemplate: "Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"
      # pullRequestTitleTemplate: "[Frogbot] Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"

    scan:
      includeAllVulnerabilities: false      # If true, includes existing vulnerabilities too
      avoidPreviousPrCommentsDeletion: false
      failOnSecurityIssues: false
      fixableOnly: true
      # minSeverity: "High"                 # Optional: Low, Medium, High, or Critical
      # emailReceivers:                     # Optional: send email alerts for secrets
      #   - user@company.com

    projects:
      # Optional: list only if needed (e.g., using Yarn 2, .NET, NuGet)
      # - workingDirs:
      #     - path/to/project-1
      #   installCommand: "npm install"
      # - workingDirs:
      #     - path/to/project-2